加入新的前端及優化後端
Zhen-Bo/flipper_gacha_simulator pull request #1
Opened 2021-10-01 15:08 UTC by bell-rabbit

Add a new UI.

Feature:
* 重新設計全個UI
* 保存最近10次的記錄
* 重新設計角色icon 顯示
* 同一個池下的角色出現率報告
* API加入TEMP的功能

![pr_1](https://user-images.githubusercontent.com/23504826/135642723-c91aec8e-a9de-4a9a-acc3-bd1809925448.gif)
![pr_2](https://user-images.githubusercontent.com/23504826/135642749-77299f8a-0078-425a-bfc2-9adbc494c64b.gif)
![pr_3](https://user-images.githubusercontent.com/23504826/135642782-5cb14f1b-1afa-46d3-9dcb-5858be91ca43.gif)
![pr_4](https://user-images.githubusercontent.com/23504826/135642800-18d29c52-ce9a-432b-b761-88e8deab7a65.gif)

2021-10-01 16:01 UTC, Zhen-Bo requested changes
暫時只有這樣,因為啟動不了,所以剩下的沒辦法去測試&處理

2021-10-01 16:01 UTC, Zhen-Bo commented on flipper_gacha.py
> +character_list_temp = {}
我用的WSGI會fork出兩個worker,全域變數有可能在兩個worker上造成資料不同部

2021-10-01 16:01 UTC, Zhen-Bo commented on flipper_gacha.py
> +@app.errorhandler(404)
由於CDN是用cloudflare,所以這個func應該不會起作用(不會顯示回傳的error)

2021-10-01 16:01 UTC, Zhen-Bo commented on vue.config.js
> +        target: 'http://192.168.100.147:5000/',
target在正式上線應該是要在port8001

2021-10-01 16:01 UTC, Zhen-Bo commented on flipper_gacha.py
> +    DATA_FOLDER=os.getenv("DATA_FOLDER"),
這個DATA_FOLDER是?我沒有對應的路徑

2021-10-01 16:01 UTC, Zhen-Bo commented on flipper_gacha.py
> +            template_folder="./templates")
好像沒看到有dist,然後template_folder應該是./public?

2021-10-01 16:01 UTC, Zhen-Bo commented on flipper_gacha.py
> +last_run_time = {}
同上,全域變數可能會有問題

2021-10-01 16:13 UTC, Zhen-Bo commented
在npm install時會出現
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 1343 packages in 11.358s

91 packages are looking for funding
  run `npm fund` for details

found 7 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

無法在ubuntu系統完成安裝

2021-10-01 16:14 UTC, bell-rabbit commented on vue.config.js
> +        target: 'http://192.168.100.147:5000/',
devServer 只是用在開發的設定，不能直接在PRD使用

2021-10-01 16:16 UTC, bell-rabbit commented on flipper_gacha.py
> +    DATA_FOLDER=os.getenv("DATA_FOLDER"),
由於static_folder轉了地方。DATA_FOLDER 是你的JSON.

VUE_APP_RESOURCE_URL=https://raw.githubusercontent.com/Zhen-Bo/flipper_gacha_simulator/main
DATA_FOLDER=./static

2021-10-01 16:17 UTC, bell-rabbit commented on flipper_gacha.py
> +            template_folder="./templates")
使用 `npm build` 來建立VUE PRD的dist及index.html ("./templates")

2021-10-01 16:20 UTC, Zhen-Bo commented on flipper_gacha.py
> +            template_folder="./templates")
主要是可能你用的套件沒法安裝在ubuntu導致npm install會失敗
還是說直接build就好?

2021-10-01 16:20 UTC, bell-rabbit commented
> 在npm install時會出現 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents): npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"}) npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents): npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"}) npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents): npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> 
> audited 1343 packages in 11.358s
> 
> 91 packages are looking for funding run `npm fund` for details
> 
> found 7 moderate severity vulnerabilities run `npm audit fix` to fix them, or `npm audit` for details
> 
> 無法在ubuntu系統完成安裝

這WARN一直會出的，你可以無視他。
直接 `npm run serve`

2021-10-01 16:22 UTC, bell-rabbit commented on flipper_gacha.py
> +character_list_temp = {}
不會不同步的， 這是個code table。
你要更改code table 的資料重開一下就好

2021-10-01 16:26 UTC, bell-rabbit commented on flipper_gacha.py
> +last_run_time = {}
同上。 character_report_temp 只是5分鐘不會再行多次。

2021-10-01 16:29 UTC, bell-rabbit commented on flipper_gacha.py
> +@app.errorhandler(404)
Cloudflare 可以回傳404 error


![image](https://user-images.githubusercontent.com/23504826/135655492-c9dbdf87-f2d2-4742-82b0-0401a232f65e.png)

2021-10-01 16:30 UTC, Zhen-Bo commented on flipper_gacha.py
> +@app.errorhandler(404)
不過不會顯示error message吧?

2021-10-01 16:30 UTC, bell-rabbit commented on flipper_gacha.py
> +            template_folder="./templates")
`npm run serve` 可以?

2021-10-01 16:31 UTC, Zhen-Bo commented
> > 在npm install時會出現 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents): npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"}) npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents): npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"}) npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents): npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> > audited 1343 packages in 11.358s
> > 91 packages are looking for funding run `npm fund` for details
> > found 7 moderate severity vulnerabilities run `npm audit fix` to fix them, or `npm audit` for details
> > 無法在ubuntu系統完成安裝
> 
> 這WARN一直會出的，你可以無視他。 直接 `npm run serve`

現在更尷尬地來了,我租借的vps是1vcpu+1Gram的,只要我一執行npm run build vps會直接卡死得手動重啟才能正常

2021-10-01 16:33 UTC, bell-rabbit commented on flipper_gacha.py
> +            template_folder="./templates")
一定會出現的

> PS C:\bell-rabbit\flipper_gacha_simulator> npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\webpack-dev-server\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

>audited 1343 packages in 5.286s

>91 packages are looking for funding
 > run `npm fund` for details

>found 7 moderate severity vulnerabilities
>  run `npm audit fix` to fix them, or `npm audit` for details

2021-10-01 16:34 UTC, Zhen-Bo commented on flipper_gacha.py
> +            template_folder="./templates")
ERROR  Failed to compile with 4 errors                                                                                                                    4:34:08 PM

This dependency was not found:

* ..\assets\bg.jpg in ./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/.cache/vue-loader","cacheIdentifier":"28508784-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/Flipper.vue?vue&type=template&id=0a314c46&scoped=true&

To install it, you can run: npm install --save ..\assets\bg.jpg


These relative modules were not found:

* ./undefined/static/image/rarity/star3.png in ./node_modules/css-loader/dist/cjs.js??ref--8-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--8-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--8-oneOf-1-3!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/CharacterIcon.vue?vue&type=style&index=0&id=266f4242&lang=scss&scoped=true&
* ./undefined/static/image/rarity/star4.png in ./node_modules/css-loader/dist/cjs.js??ref--8-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--8-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--8-oneOf-1-3!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/CharacterIcon.vue?vue&type=style&index=0&id=266f4242&lang=scss&scoped=true&
* ./undefined/static/image/rarity/star5.png in ./node_modules/css-loader/dist/cjs.js??ref--8-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--8-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--8-oneOf-1-3!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/CharacterIcon.vue?vue&type=style&index=0&id=266f4242&lang=scss&scoped=true&

2021-10-01 16:34 UTC, bell-rabbit commented
> > > 在npm install時會出現 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents): npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"}) npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents): npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"}) npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents): npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> > > audited 1343 packages in 11.358s
> > > 91 packages are looking for funding run `npm fund` for details
> > > found 7 moderate severity vulnerabilities run `npm audit fix` to fix them, or `npm audit` for details
> > > 無法在ubuntu系統完成安裝
> > 
> > 
> > 這WARN一直會出的，你可以無視他。 直接 `npm run serve`
> 
> 現在更尷尬地來了,我租借的vps是1vcpu+1Gram的,只要我一執行npm run build vps會直接卡死得手動重啟才能正常
用你自己的電腦來build. 把build 好的`./dist`及 `./templates/index.html` 放上去

2021-10-01 16:35 UTC, Zhen-Bo commented on flipper_gacha.py
> +            template_folder="./templates")
這個是npm run serve
build則會直接讓vps卡死

2021-10-01 16:37 UTC, bell-rabbit commented on flipper_gacha.py
> +            template_folder="./templates")
你自己的電腦來build.

.env 要加入新的設定
VUE_APP_RESOURCE_URL=https://raw.githubusercontent.com/Zhen-Bo/flipper_gacha_simulator/main
DATA_FOLDER=./static

2021-10-01 16:39 UTC, bell-rabbit commented on flipper_gacha.py
> +@app.errorhandler(404)
會出。 這是個apache 404頁。

![image](https://user-images.githubusercontent.com/23504826/135656779-4132c4ef-aa2c-48b3-b38e-2e2a3b7de9f6.png)

2021-10-01 16:40 UTC, bell-rabbit commented on flipper_gacha.py
> +@app.errorhandler(404)
https://www.paverschlev.link/wf/flipper/34
你可以去看看

2021-10-01 16:43 UTC, bell-rabbit commented on flipper_gacha.py
> +            template_folder="./templates")
npm run serve 是同來local dev 用的

2021-10-01 16:43 UTC, bell-rabbit commented on flipper_gacha.py
> +            template_folder="./templates")
https://book.vue.tw/CH3/3-3-vue-dev-server-build.html

2021-10-01 16:55 UTC, Zhen-Bo commented
> > > > 在npm install時會出現 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents): npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"}) npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents): npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"}) npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents): npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> > > > audited 1343 packages in 11.358s
> > > > 91 packages are looking for funding run `npm fund` for details
> > > > found 7 moderate severity vulnerabilities run `npm audit fix` to fix them, or `npm audit` for details
> > > > 無法在ubuntu系統完成安裝
> > > 
> > > 
> > > 這WARN一直會出的，你可以無視他。 直接 `npm run serve`
> > 
> > 
> > 現在更尷尬地來了,我租借的vps是1vcpu+1Gram的,只要我一執行npm run build vps會直接卡死得手動重啟才能正常
> 
> 用你自己的電腦來build. 把build 好的`./dist`及 `./templates/index.html` 放上去

 ERROR  Failed to compile with 1 error                                                                                                                                          上午12:53:03
 error  in ./src/components/CharacterIcon.vue?vue&type=style&index=0&id=fe104aec&lang=scss&scoped=true&

Syntax Error: ModuleNotFoundError: Module not found: Error: Can't resolve './undefined/static/image/rarity/star3.png' in 'C:\Users\Paver\Documents\GitHub\flipper_gacha_simulator\src\components'


 @ ./src/components/CharacterIcon.vue?vue&type=style&index=0&id=fe104aec&lang=scss&scoped=true& 1:0-535 1:0-535
 @ ./src/components/CharacterIcon.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/CharacterReport.vue?vue&type=script&lang=js&
 @ ./src/components/CharacterReport.vue?vue&type=script&lang=js&
 @ ./src/components/CharacterReport.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/Report.vue?vue&type=script&lang=js&
 @ ./src/views/Report.vue?vue&type=script&lang=js&
 @ ./src/views/Report.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./src/main.js

 ERROR  Build failed with errors.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! flipper_gacha_simulator@0.1.0 build: `vue-cli-service build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the flipper_gacha_simulator@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

在自己電腦build的時候出error
LOG:

18 verbose node v14.18.0
19 verbose npm  v6.14.15
20 error code ELIFECYCLE
21 error errno 1
22 error flipper_gacha_simulator@0.1.0 build: `vue-cli-service build`
22 error Exit status 1
23 error Failed at the flipper_gacha_simulator@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

2021-10-01 16:57 UTC, bell-rabbit commented
> > > > > 在npm install時會出現 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents): npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"}) npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents): npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"}) npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents): npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> > > > > audited 1343 packages in 11.358s
> > > > > 91 packages are looking for funding run `npm fund` for details
> > > > > found 7 moderate severity vulnerabilities run `npm audit fix` to fix them, or `npm audit` for details
> > > > > 無法在ubuntu系統完成安裝
> > > > 
> > > > 
> > > > 這WARN一直會出的，你可以無視他。 直接 `npm run serve`
> > > 
> > > 
> > > 現在更尷尬地來了,我租借的vps是1vcpu+1Gram的,只要我一執行npm run build vps會直接卡死得手動重啟才能正常
> > 
> > 
> > 用你自己的電腦來build. 把build 好的`./dist`及 `./templates/index.html` 放上去
> 
> ERROR Failed to compile with 1 error 上午12:53:03 error in ./src/components/CharacterIcon.vue?vue&type=style&index=0&id=fe104aec&lang=scss&scoped=true&
> 
> Syntax Error: ModuleNotFoundError: Module not found: Error: Can't resolve './undefined/static/image/rarity/star3.png' in 'C:\Users\Paver\Documents\GitHub\flipper_gacha_simulator\src\components'
> 
> @ ./src/components/CharacterIcon.vue?vue&type=style&index=0&id=fe104aec&lang=scss&scoped=true& 1:0-535 1:0-535 @ ./src/components/CharacterIcon.vue @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/CharacterReport.vue?vue&type=script&lang=js& @ ./src/components/CharacterReport.vue?vue&type=script&lang=js& @ ./src/components/CharacterReport.vue @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/Report.vue?vue&type=script&lang=js& @ ./src/views/Report.vue?vue&type=script&lang=js& @ ./src/views/Report.vue @ ./src/router/index.js @ ./src/main.js @ multi ./src/main.js
> 
> ERROR Build failed with errors. npm ERR! code ELIFECYCLE npm ERR! errno 1 npm ERR! flipper_gacha_simulator@0.1.0 build: `vue-cli-service build` npm ERR! Exit status 1 npm ERR! npm ERR! Failed at the flipper_gacha_simulator@0.1.0 build script. npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> 在自己電腦build的時候出error LOG:
> 
> 18 verbose node v14.18.0 19 verbose npm v6.14.15 20 error code ELIFECYCLE 21 error errno 1 22 error flipper_gacha_simulator@0.1.0 build: `vue-cli-service build` 22 error Exit status 1 23 error Failed at the flipper_gacha_simulator@0.1.0 build script. 23 error This is probably not a problem with npm. There is likely additional logging output above. 24 verbose exit [ 1, true ]

.env 沒加上新的key 吧

2021-10-01 17:23 UTC, Zhen-Bo commented
build完後把dict跟index.html放到對應的地方後還有要做什麼嗎?
我看畫面整個都是白的沒東西,也沒有跳出noscript的警告
body
`<body><noscript><strong>We're sorry but flipper_gacha_simulator doesn't work properly without JavaScript enabled. Please enable it to continue.</strong></noscript><div id="app"></div><script src="/js/chunk-vendors.2de79c06.js"></script><script src="/js/app.4fbdecff.js"></script><script defer="" src="https://static.cloudflareinsights.com/beacon.min.js" data-cf-beacon="{&quot;rayId&quot;:&quot;69775f667fac0ca7&quot;,&quot;version&quot;:&quot;2021.9.0&quot;,&quot;r&quot;:1,&quot;token&quot;:&quot;0d253e5e3cf940f885a857f4aca9fa94&quot;,&quot;si&quot;:100}"></script>
</body>`

2021-10-01 17:36 UTC, Zhen-Bo commented
我目前把網站架設到/wf_test上面測試,不過我發現只要輸入https://www.paverschlev.link/wf_test後
他會自動把網址改寫成https://www.paverschlev.link/flipper
在 `/` 下面我有另一個APP再跑,所以會導致刷新後會變成404
要在哪邊才能修改會重寫網址的code
`/` ->一個APP
`/wf_test` ->測試用,也是單獨一個APP
`/wf`->現在的抽卡程式APP

2021-10-01 17:43 UTC, bell-rabbit commented
> 我目前把網站架設到/wf_test上面測試,不過我發現只要輸入[https://www.paverschlev.link/wf_test後](https://www.paverschlev.link/wf_test%E5%BE%8C) 他會自動把網址改寫成https://www.paverschlev.link/flipper 在 `/` 下面我有另一個APP再跑,所以會導致刷新後會變成404 要在哪邊才能修改會重寫網址的code `/` ->一個APP `/wf_test` ->測試用,也是單獨一個APP `/wf`->現在的抽卡程式APP

由於我不知道你會放在那網址
你要手動設定一下 加上 /wf_test
再重新build 一次

`src/router/index.js`
`templates/`

2021-10-01 17:57 UTC, Zhen-Bo commented
![image](https://user-images.githubusercontent.com/30999421/135665080-e3ee742a-60d3-4e48-827e-18baa0fa4543.png)
想問下最下面那個footer可不可以把額外兩邊的白色(框起來的部分)取消掉?
![image](https://user-images.githubusercontent.com/30999421/135665457-5cb4e080-9ba8-4b95-8254-acc809c157ca.png)
然後顯示的部分那個container可以把mt-2的class拿掉嗎?不然margin-top :8px是important會一直有空格
再來我覺得nav留下卡池切換的部分就好,那個彈射抽卡模擬的那條可以拿掉

自己的想像情況:
剛好是100vh
![image](https://user-images.githubusercontent.com/30999421/135665903-cca4fabf-61fc-42c2-99f4-6c6a819b6161.png)

2021-10-01 17:59 UTC, Zhen-Bo commented
剩下的我明天處理,先去睡了,反正明天應該會先上線,出事了再慢慢修就好

2021-10-03 14:47 UTC, Zhen-Bo commented
感謝修改,不過這幾天都有排面試要準備所以可能要等之後有空才能更新Orz

2021-10-03 14:48 UTC, bell-rabbit commented
已更新
![image](https://user-images.githubusercontent.com/23504826/135759082-286c8187-0b17-4822-be40-bfd3819f98d1.png)

假如你要把圖片分開來放 要加入這個新的file
`flipper_gacha_simulator\src\assets\bg.jpg`

2021-10-03 14:52 UTC, Zhen-Bo commented
> 已更新 ![image](https://user-images.githubusercontent.com/23504826/135759082-286c8187-0b17-4822-be40-bfd3819f98d1.png)
> 
> 假如你要把圖片分開來放 要加入這個新的file `flipper_gacha_simulator\src\assets\bg.jpg`
圖片分開放是啥意思,有點不太懂@@
然後你是說在build的時候就要有bg.jpg在assets這個資料夾內?我記得那個好像是個空白圖片...嗎?

2021-10-03 14:57 UTC, Zhen-Bo commented
喔喔沒事了,我看到了

2021-10-04 05:52 UTC, Zhen-Bo approved these changes
LGTM

2021-10-04 05:52 UTC, merged